server {
    listen 80;
    listen [::]:80;
    server_name asistente-test.vieterre.tech;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
